#!/usr/bin/env python3
"""Generate a C harness that runs the recompiler's own output against the
SingleStepTests m68000 vectors.

This is verification layer 1: ground truth at the instruction level, with no
game, VDP, Z80 or timing involved. A failure names an exact opcode and an exact
register, instead of "something is wrong somewhere in 9445 blocks".

Because db4a is a static recompiler, the natural way to test it is to generate
code for each vector's instruction exactly as the real build would, then run
it. That exercises the shipping path rather than a separate interpreter.

usage: gen_vector_test.py <out.c> <vectors-dir> [per-file-limit] [name ...]
"""
import os, sys, glob
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'tools'))
import m68ktest, ea, semantics
from capstone import Cs, CS_ARCH_M68K, CS_MODE_M68K_000

PRELUDE = '''/* GENERATED by tests/gen_vector_test.py -- do not edit. */
#include "m68k.h"
#include <stdio.h>
#include <string.h>
m68k_t CPU;
static uint8_t MEM[0x1000000];
uint8_t  m68k_read8 (uint32_t a){return MEM[a&0xFFFFFF];}
uint16_t m68k_read16(uint32_t a){a&=0xFFFFFF;return (uint16_t)((MEM[a]<<8)|MEM[a+1]);}
uint32_t m68k_read32(uint32_t a){return ((uint32_t)m68k_read16(a)<<16)|m68k_read16(a+2);}
void m68k_write8 (uint32_t a,uint8_t v){MEM[a&0xFFFFFF]=v;}
void m68k_write16(uint32_t a,uint16_t v){a&=0xFFFFFF;MEM[a]=(uint8_t)(v>>8);MEM[a+1]=(uint8_t)v;}
void m68k_write32(uint32_t a,uint32_t v){m68k_write16(a,(uint16_t)(v>>16));m68k_write16(a+2,(uint16_t)v);}
void set_sr(uint16_t v){ set_ccr((uint8_t)(v & 0xFF)); CPU.imask=(v>>8)&7; CPU.super=(v>>13)&1; }
void m68k_div_by_zero(void){}
void m68k_illegal(uint32_t pc){(void)pc;}
void m68k_unimplemented(uint32_t pc){(void)pc;}

static unsigned pass_n, fail_n, run_n;
static const char *cur_group;
static unsigned group_fail, this_fail;

static void bad(const char *name, const char *what, uint32_t got, uint32_t want) {
    fail_n++; this_fail++;
    if (group_fail++ < 3)
        printf("   FAIL %-22s %-10s got %08X want %08X\\n", name, what, got, want);
}
#define CKR(name, what, got, want) do { \\
    if ((uint32_t)(got) != (uint32_t)(want)) bad(name, what, (uint32_t)(got), (uint32_t)(want)); \\
    } while (0)
'''

def emit_test(fn_name, t, insn_addr, mnemonic, op_str):
    """C for one vector, or None if we cannot generate code for it."""
    try:
        ops = ea.parse(op_str)
        stmts = semantics.emit(mnemonic, ops, semantics.Ctx(insn_addr, 2, insn_addr + 2))
    except Exception:
        return None

    i, f = t['initial'], t['final']
    sup = (i['sr'] >> 13) & 1
    out = ["static void %s(void) {" % fn_name,
           '  const char *N = "%s";' % t['name'].replace('"', "'"),
           "  this_fail = 0;"]
    # initial state
    for r in range(8):
        out.append("  CPU.d[%d] = 0x%Xu;" % (r, i['d%d' % r]))
    for r in range(7):
        out.append("  CPU.a[%d] = 0x%Xu;" % (r, i['a%d' % r]))
    out.append("  CPU.usp = 0x%Xu; CPU.ssp = 0x%Xu;" % (i['usp'], i['ssp']))
    out.append("  CPU.a[7] = 0x%Xu;" % (i['ssp'] if sup else i['usp']))
    out.append("  set_sr(0x%Xu);" % i['sr'])
    # initial memory (only the cells the vector specifies)
    for addr, val in sorted(i['ram'].items()):
        out.append("  MEM[0x%Xu] = 0x%02Xu;" % (addr & 0xFFFFFF, val))
    # the instruction itself
    out.append("  { /* %s %s */" % (mnemonic, op_str))
    for st in stmts:
        out.append("    " + st)
    out.append("  }")
    # compare
    for r in range(8):
        out.append('  CKR(N, "d%d", CPU.d[%d], 0x%Xu);' % (r, r, f['d%d' % r]))
    for r in range(7):
        out.append('  CKR(N, "a%d", CPU.a[%d], 0x%Xu);' % (r, r, f['a%d' % r]))
    out.append('  CKR(N, "sp", CPU.a[7], 0x%Xu);' % (f['ssp'] if sup else f['usp']))
    out.append('  CKR(N, "ccr", get_sr() & 0x1Fu, 0x%Xu);' % (f['sr'] & 0x1F))
    for addr, val in sorted(f['ram'].items()):
        out.append('  CKR(N, "mem%06X", MEM[0x%Xu], 0x%02Xu);'
                   % (addr & 0xFFFFFF, addr & 0xFFFFFF, val))
    out.append("  run_n++; if (!this_fail) pass_n++;")
    out.append("}")
    return "\n".join(out)

def main():
    out_path = sys.argv[1]
    vdir     = sys.argv[2]
    limit    = int(sys.argv[3]) if len(sys.argv) > 3 else 150
    only     = sys.argv[4:]

    md = Cs(CS_ARCH_M68K, CS_MODE_M68K_000)
    md.detail = False

    files = sorted(glob.glob(os.path.join(vdir, '*.json.bin')))
    if only:
        files = [f for f in files
                 if os.path.basename(f).replace('.json.bin','') in only]
    if not files:
        raise SystemExit("no vector files found in %s" % vdir)

    bodies, calls, skipped, skipped_trap = [], [], {}, {}
    for path in files:
        group = os.path.basename(path).replace('.json.bin', '')
        tests = m68ktest.load(path, limit=limit)
        n_ok = 0
        for k, t in enumerate(tests):
            addr, raw = m68ktest.instr_bytes(t)
            try:
                ins = next(md.disasm(raw, addr, 1))
            except StopIteration:
                skipped[group] = skipped.get(group, 0) + 1
                continue
            # Address errors and other traps push an exception frame and force
            # supervisor mode. db4a does not implement exception entry, so
            # these are out of scope rather than failures; excluding them keeps
            # the signal honest instead of drowning it in known-missing cases.
            if t.get('addr_error') or \
               (((t['final']['sr'] >> 13) & 1) and not ((t['initial']['sr'] >> 13) & 1)):
                skipped_trap[group] = skipped_trap.get(group, 0) + 1
                continue
            fn = "t_%s_%d" % (group.replace('.', '_').replace('-', '_'), k)
            body = emit_test(fn, t, addr, ins.mnemonic, ins.op_str)
            if body is None:
                skipped[group] = skipped.get(group, 0) + 1
                continue
            bodies.append(body)
            calls.append((group, fn))
            n_ok += 1
        print("  %-12s %4d tests" % (group, n_ok))

    src = [PRELUDE]
    src += bodies
    src.append("int main(void) {")
    last = None
    for group, fn in calls:
        if group != last:
            src.append('  cur_group = "%s"; group_fail = 0;' % group)
            src.append('  printf("-- %s\\n");' % group)
            last = group
        src.append("  memset(MEM, 0, sizeof MEM); %s();" % fn)
    src.append('  printf("\\nvectors: %u/%u passed, %u mismatches\\n", pass_n, run_n, fail_n);')
    src.append("  return fail_n != 0;")
    src.append("}")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    open(out_path, 'w').write("\n".join(src) + "\n")
    total = len(calls)
    print("generated %s: %d vectors" % (out_path, total))
    if skipped:
        print("skipped (no decode / unsupported form):", skipped)
    if skipped_trap:
        print("skipped (traps into an exception -- not implemented):", skipped_trap)

main()
