#!/usr/bin/env python3
"""Recompiler backend: turn discovered basic blocks into C.

Each basic block becomes a function returning the next PC:

    uint32_t blk_000200(void) { ...; return 0x20Eu; }

A dispatch loop drives execution, so there is no unbounded C stack growth and
an indirect transfer is simply a computed return value.

Block boundaries start at any function entry, any branch target, and any
instruction following a terminal one; they end at a terminal instruction or
just before the next boundary.
"""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ea, semantics, timing, struct

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def _load_rom():
    import glob
    for p in glob.glob(os.path.join(ROOT, 'roms', '*', '*.bin')):
        if '[' not in os.path.basename(p):
            return open(p, 'rb').read()
    return None
ROM_BYTES = _load_rom()

def block_starts(insns, order, starts, xrefs):
    b = set(starts)
    for a in order:
        sz, mn, op = insns[a]
        if semantics.is_terminal(mn):
            nxt = a + sz
            if nxt in insns:
                b.add(nxt)
    for t in xrefs:
        if t in insns:
            b.add(t)
    b.add(order[0])
    return b

# capstone mis-decodes ROXL/ROXR when the shift count comes from a register:
# 0xEC31 is ROXR.B D6,D1 but is reported as "roxr.l #$6, d1" -- wrong size and
# wrong count source. Verified against m68k-linux-gnu-objdump. This ROM contains
# no such instruction (its three ROX uses are all immediate-count), but silently
# generating wrong code for another ROM would be far worse than refusing to.
def capstone_misdecodes(rom, addr, mnemonic):
    if mnemonic.split('.')[0] not in ('roxl', 'roxr'):
        return False
    w = struct.unpack(">H", rom[addr:addr+2])[0]
    return (w & 0xF000) == 0xE000 and (w & 0x20) and (w & 0xC0) != 0xC0

def main():
    cm = json.load(open(os.path.join(ROOT, 'build', 'codemap.json')))
    rom_path = cm.get('rom_path')
    insns = {int(k, 16): tuple(v) for k, v in cm['insns'].items()}
    order = sorted(insns)
    starts = {int(x, 16) for x in cm['starts']}
    xrefs  = {int(x, 16) for x in cm['xrefs']}
    bstart = block_starts(insns, order, starts, xrefs)

    out = ['/* GENERATED by tools/recomp.py -- do not edit.',
           ' * Fix semantics in tools/semantics.py and regenerate. */',
           '#include "m68k.h"', '']
    blocks = []
    i = 0
    nfail = 0
    while i < len(order):
        a = order[i]
        body = []
        timed = []          # (mnemonic, operands, size) for the cycle estimate
        cur = a
        j = i
        while j < len(order):
            addr = order[j]
            if addr != cur:
                break                      # gap: data between instructions
            sz, mn, op = insns[addr]
            if ROM_BYTES and capstone_misdecodes(ROM_BYTES, addr, mn):
                raise SystemExit(
                    "refusing to generate: capstone mis-decodes the register-count "
                    "ROX form at %06X (%s %s). See tools/recomp.py." % (addr, mn, op))
            try:
                parsed = ea.parse(op)
                _, isz = semantics.split_mnemonic(mn)
                timed.append((mn, parsed, isz or 'w'))
                stmts = semantics.emit(mn, parsed, semantics.Ctx(addr, sz, addr + sz))
            except Exception as e:
                stmts = ['m68k_unimplemented(0x%Xu); return 0x%Xu;' % (addr, addr + sz)]
                nfail += 1
            # Each instruction gets its own scope so temporaries cannot
            # collide with a neighbour's inside the same block.
            body.append('  { /* %06X  %-8s %s */' % (addr, mn, op))
            body += ['    ' + s for s in stmts]
            body.append('  }')
            cur = addr + sz
            j += 1
            if semantics.is_terminal(mn):
                break
            if cur in bstart:
                body.append('  return 0x%Xu;' % cur)
                break
        else:
            pass
        if not any(l.strip().startswith('return') for l in body[-3:]):
            body.append('  return 0x%Xu;' % cur)
        out.append('static uint32_t blk_%06X(void) {' % a)
        # Cycle cost is fixed per block and known at generation time, so it is
        # a constant here rather than an accumulation per instruction.
        out.append('  CPU.cycles += %d;' % timing.block_cycles(timed))
        out += body
        out.append('}')
        out.append('')
        blocks.append(a)
        i = j if j > i else i + 1

    # PC -> block lookup, binary-searched at runtime
    out.append('const uint32_t BLOCK_ADDR[] = {')
    out += ['  0x%Xu,' % b for b in blocks]
    out.append('};')
    out.append('uint32_t (*const BLOCK_FN[])(void) = {')
    out += ['  blk_%06X,' % b for b in blocks]
    out.append('};')
    out.append('const unsigned BLOCK_COUNT = %d;' % len(blocks))

    dst = os.path.join(ROOT, 'src', 'gen', 'blocks.c')
    open(dst, 'w').write('\n'.join(out) + '\n')
    print('blocks emitted   : %d' % len(blocks))
    print('PAL frame budget : %d cycles' % timing.PAL_FRAME_CYCLES)
    print('instructions     : %d' % len(order))
    print('unimplemented    : %d' % nfail)
    print('wrote %s (%d lines)' % (dst, len(out)))

main()
